# Generated by Django 5.0.6 on 2024-07-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_cor_options_alter_marca_nacionalidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessorio",
            old_name="categoria",
            new_name="nome",
        ),
    ]
